# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: SGTSGI Forum

# Short description (goes below the title; it will also be used in the RSS feed)
description: Structural Geology and Tectonic Studies Group-India

# Your name, as you want it to appear underneath each post and in the footer
author: SGTSGI

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
baseurl: /forum
# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://sgtsgi.github.io/forum

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: sgtsgiforum

# The public key for your disqus application
disqus_publickey: 4vDjpnfgQ95ET57cMRPGhF7gRNCWbUzz9swl3jlfmxZiHJAQvJnk41hNyovrGWLN


